name: 'Get the datetime string'
description: 'use it to get the datetime.'
inputs:
  test:
    description: 'input test'
    required: true
    default: 'xxx'
outputs:
  datetime: #
    description: 'date and time'
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'


